import { eq } from "drizzle-orm";
import { getDb } from "@/db";
import * as s from "@/db/schema";
import { actor, engagementEligibility, seedIfEmpty } from "@/lib/server-data";
import { canReview, requirePermission } from "@/lib/authz";
import { errorResponse } from "@/lib/http";
import { safeDownloadName, securityHeaders } from "@/lib/security";
import { conclusionCompatibility, isConcernClosed } from "@/lib/concerns";

export const dynamic="force-dynamic";
export async function GET(request:Request){
 try{
  await seedIfEmpty();const who=await actor();requirePermission(canReview(who),"Reviewer permission is required"); const id=Number(new URL(request.url).searchParams.get("engagementId")); const db=getDb(); const row=(await db.select({eng:s.engagements,client:s.clients}).from(s.engagements).innerJoin(s.clients,eq(s.engagements.clientId,s.clients.id)).where(eq(s.engagements.id,id)).limit(1))[0]; if(!row)return new Response("Engagement not found",{status:404});
  const tasks=await db.select().from(s.tasks).where(eq(s.tasks.engagementId,id)); const taskIds=new Set(tasks.map(t=>t.id));const procedures=(await db.select().from(s.procedures)).filter(p=>taskIds.has(p.taskId));const notes=await db.select().from(s.reviewNotes).where(eq(s.reviewNotes.engagementId,id));const concerns=await db.select().from(s.concerns).where(eq(s.concerns.engagementId,id)),tbVersions=await db.select().from(s.tbImports).where(eq(s.tbImports.engagementId,id)); const eligibility=await engagementEligibility(row.eng); const coreReady=tasks.filter(task=>!task.isCustom).every(task=>task.status==="REVIEWED");const proceduresReady=procedures.every(p=>p.status==="REVIEWED"&&(p.applicability!=="NOT_APPLICABLE"||Boolean(p.applicabilityRationale))),latestTb=tbVersions.sort((a,b)=>b.version-a.version)[0],tbReady=row.eng.accountingBasis!=="Accruals"||latestTb?.status==="REVIEWED",qualityReady=row.eng.qualityReviewMode==="NONE"||row.eng.qualityReviewStatus==="COMPLETED",compatibility=conclusionCompatibility(row.eng.reportConclusion,concerns);const ready=!row.eng.lockedAt&&eligibility.eligible&&eligibility.scrutiny==="INDEPENDENT_EXAMINATION"&&coreReady&&proceduresReady&&tbReady&&notes.every(n=>n.status==="CLEARED")&&concerns.every(c=>isConcernClosed(c.status))&&qualityReady&&row.eng.trusteeApproved&&row.eng.materialSignificanceAssessed&&compatibility.compatible; if(!ready)return Response.json({error:eligibility.eligible?`Completion controls are not satisfied. ${compatibility.reason}`:eligibility.reason},{status:409});
  const statements:Record<string,string>={UNMODIFIED:"I have completed my examination. No material matters have come to my attention giving me cause to believe that in any material respect the accounting records were not kept as required, the accounts do not accord with those records, or the accounts do not comply with the applicable requirements concerning their form and content. I have no concerns and have come across no other matters to which attention should be drawn to enable a proper understanding of the accounts.",RECORDS_CONCERN:"In the course of my examination, material matters came to my attention concerning whether sufficient accounting records have been kept. The matters identified are set out in the controlled findings accompanying this report.",ACCOUNTS_CONCERN:"In the course of my examination, material matters came to my attention concerning whether the accounts accord with the accounting records or comply with the applicable requirements concerning their form and content. The matters identified are set out in the controlled findings accompanying this report.",OTHER_MATTER:"I have completed my examination. Other matters came to my attention which should be drawn to the reader's attention to enable a proper understanding of the accounts. Those matters are set out in the controlled findings accompanying this report."};
  const basis:Record<string,string>={ENGLAND_WALES:"the Charities Act 2011 and the applicable Directions issued by the Charity Commission for England and Wales",SCOTLAND:"the Charities and Trustee Investment (Scotland) Act 2005 and the Charities Accounts (Scotland) Regulations 2006, as amended",NORTHERN_IRELAND:"the Charities Act (Northern Ireland) 2008, applicable regulations and Charity Commission for Northern Ireland guidance"};
  const date=new Date(row.eng.periodEnd).toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"}); const charity=escapeHtml(row.client.name); const statement=statements[row.eng.reportConclusion!]||statements.UNMODIFIED; const reportFindings=concerns.filter(c=>isConcernClosed(c.status)&&!["NO_REPORTING_EFFECT","UNDETERMINED"].includes(c.reportingAssessment)).map(c=>`<li><strong>${escapeHtml(c.reference)}</strong>: ${escapeHtml(c.examinerConclusion||c.resolution||c.description)}</li>`).join(""); const findingsSection=reportFindings?`<h2>Controlled findings</h2><ul>${reportFindings}</ul>`:""; const html=`<!doctype html><html><head><meta charset="utf-8"><title>Independent examiner's report</title><style>body{font-family:Arial,sans-serif;max-width:760px;margin:60px auto;color:#2d2d2d;line-height:1.55}h1{text-align:center;font-size:20px}h2{font-size:14px;margin-top:26px}.sig{margin-top:50px;border-top:1px solid #aaa;padding-top:15px}</style></head><body><p style="text-align:center;font-size:11px;font-weight:bold">INDEPENDENT EXAMINER'S REPORT TO THE TRUSTEES OF</p><h1>${charity}</h1><p>I report to the charity trustees on my examination of the accounts of the charity for the year ended ${date}.</p><h2>Responsibilities and basis of report</h2><p>As the charity trustees you are responsible for the preparation of the accounts under the law and reporting framework applicable to the charity.</p><p>I carried out my examination under ${escapeHtml(basis[row.eng.jurisdiction]||"the applicable charity law and regulatory guidance")}. The work is a limited-assurance independent examination and not an audit.</p><h2>Independent examiner's statement</h2><p>${escapeHtml(statement)}</p>${findingsSection}<div class="sig"><strong>Dennis O'Higgins</strong><br>Independent Examiner<br>${new Date().toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"})}</div></body></html>`;
  return new Response(html,{headers:{...securityHeaders(),"Content-Type":"application/msword; charset=utf-8","Content-Disposition":`attachment; filename="${safeDownloadName(row.client.name)}-independent-examiner-report.doc"`,"Cache-Control":"no-store"}});
 }catch(error){return errorResponse(error,"Unable to generate report")}
}

function escapeHtml(value:string){return value.replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch]!))}
