CREATE TABLE `tb_accounts` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`tb_import_id` integer NOT NULL,
	`account_code` text NOT NULL,
	`account_name` text NOT NULL,
	`fund` text DEFAULT 'Unrestricted' NOT NULL,
	`statement_line` text DEFAULT 'UNMAPPED' NOT NULL,
	`note_reference` text DEFAULT '' NOT NULL,
	`debit` real DEFAULT 0 NOT NULL,
	`credit` real DEFAULT 0 NOT NULL,
	`current_balance` real DEFAULT 0 NOT NULL,
	`prior_balance` real DEFAULT 0 NOT NULL,
	`budget_balance` real DEFAULT 0 NOT NULL,
	`mapping_status` text DEFAULT 'UNMAPPED' NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`tb_import_id`) REFERENCES `tb_imports`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `tb_analytics` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`engagement_id` integer NOT NULL,
	`tb_import_id` integer NOT NULL,
	`account_id` integer,
	`type` text NOT NULL,
	`title` text NOT NULL,
	`expectation` text NOT NULL,
	`actual` real DEFAULT 0 NOT NULL,
	`comparator` real DEFAULT 0 NOT NULL,
	`variance` real DEFAULT 0 NOT NULL,
	`variance_percent` real DEFAULT 0 NOT NULL,
	`significance_threshold` real DEFAULT 0 NOT NULL,
	`severity` text DEFAULT 'MEDIUM' NOT NULL,
	`status` text DEFAULT 'OPEN' NOT NULL,
	`explanation` text DEFAULT '' NOT NULL,
	`targeted_work` text DEFAULT '' NOT NULL,
	`conclusion` text DEFAULT '' NOT NULL,
	`linked_task_id` integer,
	`linked_procedure_id` integer,
	`concern_id` integer,
	`prepared_by` text,
	`prepared_at` text,
	`reviewed_by` text,
	`reviewed_at` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`engagement_id`) REFERENCES `engagements`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`tb_import_id`) REFERENCES `tb_imports`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`account_id`) REFERENCES `tb_accounts`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`linked_task_id`) REFERENCES `tasks`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`linked_procedure_id`) REFERENCES `procedures`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`concern_id`) REFERENCES `concerns`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `tb_imports` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`engagement_id` integer NOT NULL,
	`document_id` integer,
	`version` integer NOT NULL,
	`file_name` text NOT NULL,
	`source_format` text DEFAULT 'CSV' NOT NULL,
	`status` text DEFAULT 'IMPORTED' NOT NULL,
	`row_count` integer DEFAULT 0 NOT NULL,
	`debit_total` real DEFAULT 0 NOT NULL,
	`credit_total` real DEFAULT 0 NOT NULL,
	`net_total` real DEFAULT 0 NOT NULL,
	`is_balanced` integer DEFAULT false NOT NULL,
	`validation_issues` text DEFAULT '[]' NOT NULL,
	`analysis_conclusion` text DEFAULT '' NOT NULL,
	`prepared_by` text,
	`prepared_at` text,
	`reviewed_by` text,
	`reviewed_at` text,
	`uploaded_by` text NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`engagement_id`) REFERENCES `engagements`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`document_id`) REFERENCES `documents`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `tb_reconciliations` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`engagement_id` integer NOT NULL,
	`tb_import_id` integer NOT NULL,
	`statement_line` text NOT NULL,
	`tb_amount` real DEFAULT 0 NOT NULL,
	`accounts_amount` real DEFAULT 0 NOT NULL,
	`difference` real DEFAULT 0 NOT NULL,
	`status` text DEFAULT 'NOT_RECONCILED' NOT NULL,
	`explanation` text DEFAULT '' NOT NULL,
	`prepared_by` text,
	`prepared_at` text,
	`reviewed_by` text,
	`reviewed_at` text,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FOREIGN KEY (`engagement_id`) REFERENCES `engagements`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`tb_import_id`) REFERENCES `tb_imports`(`id`) ON UPDATE no action ON DELETE no action
);
