"use client";

import { useRef, useState } from "react";
import Link from "next/link";
import { Check, CheckCircle2, ChevronDown, Clock3, File, FileText, LockKeyhole, MessageSquare, Paperclip, Send, ShieldCheck, UploadCloud } from "lucide-react";
import { Logo } from "./logo";

export function ClientPortal() {
  const input = useRef<HTMLInputElement>(null);
  const [uploaded, setUploaded] = useState<string[]>([]);
  const [message, setMessage] = useState("");
  const [sent, setSent] = useState(false);
  return <div className="portal-shell"><header className="portal-header"><Logo /><div><span className="secure"><LockKeyhole /> Secure client portal</span><button><span className="avatar client-avatar">SW</span>Sarah Whitfield<ChevronDown /></button></div></header><main className="portal-main"><div className="portal-welcome"><div><p className="eyebrow">WILLOW COMMUNITY FOUNDATION</p><h1>Good afternoon, Sarah</h1><p>D O&apos;Higgins & Co is completing your independent examination for the year ended 31 March 2026.</p></div><div className="portal-status"><span>Examination status</span><strong>Fieldwork in progress</strong><i><b /></i><small>Estimated completion: 4 September 2026</small></div></div>
      <div className="portal-grid"><section><div className="portal-section-title"><div><h2>Information requested</h2><p>Please respond to the outstanding items below.</p></div><span>2 outstanding</span></div>
        <article className="request-card urgent"><div className="request-card-head"><span className="file-icon"><FileText /></span><div><span className="overdue">OVERDUE</span><h3>Trustee declarations and interests</h3><p>Requested by Dennis O&apos;Higgins · REQ-017</p></div></div><div className="request-body"><p>Please provide completed declarations of interests for every trustee serving during the year, including confirmations where there are no interests to declare.</p><div className="due"><Clock3 /><span><small>Due date</small><strong>14 August 2026</strong></span></div><div className={`drop-zone ${uploaded.length ? "has-files" : ""}`} onClick={() => input.current?.click()}><input ref={input} type="file" multiple onChange={e => setUploaded(Array.from(e.target.files ?? []).map(f => f.name))} />{uploaded.length ? <><CheckCircle2 /><strong>{uploaded.length} file{uploaded.length > 1 ? "s" : ""} ready</strong>{uploaded.map(f => <small key={f}><File size={14} />{f}</small>)}</> : <><UploadCloud /><strong>Drop files here or click to upload</strong><small>PDF, Word, Excel, JPG or PNG · Maximum 25 MB each</small></>}</div><textarea value={message} onChange={e => setMessage(e.target.value)} placeholder="Add a note for your examiner (optional)" /><button className="primary wide" onClick={() => setSent(true)} disabled={!uploaded.length}>{sent ? <><Check /> Response submitted</> : <><Send /> Submit response</>}</button></div></article>
        <article className="request-card collapsed"><span className="file-icon amber"><FileText /></span><div><span className="due-soon">DUE IN 3 DAYS</span><h3>Restricted funds reconciliation</h3><p>Requested by Dennis O&apos;Higgins · REQ-018</p></div><button>View request</button></article>
        <div className="completed-request"><CheckCircle2 /><span><strong>July bank statement and reconciliation</strong><small>Submitted 14 August 2026 · 2 files</small></span><b>Received</b></div>
      </section><aside><div className="portal-side-card"><h2>Your engagement</h2><dl><div><dt>Reporting period</dt><dd>31 March 2026</dd></div><div><dt>Engagement lead</dt><dd>Dennis O&apos;Higgins</dd></div><div><dt>Charity number</dt><dd>1187421</dd></div><div><dt>Accounting basis</dt><dd>Accruals</dd></div></dl><Link href="/">View engagement details</Link></div><div className="portal-side-card contact"><span className="avatar large">DO</span><h3>Dennis O&apos;Higgins</h3><p>Independent Examiner</p><button><MessageSquare /> Send a secure message</button></div><div className="security-note"><ShieldCheck /><p><strong>Your information is protected</strong>Files are encrypted in transit and at rest. Access is restricted to the assigned engagement team.</p></div></aside></div>
    </main><footer className="portal-footer"><span>Powered by <strong>clarity</strong></span><span><a>Privacy</a><a>Security</a><a>Help</a></span></footer></div>;
}
