export type TaskStatus =
  | "NOT_STARTED"
  | "IN_PROGRESS"
  | "PREPARED"
  | "REVIEWED";
export type PublicId = string;
export type Client = {
  id: PublicId;
  publicId: PublicId;
  name: string;
  charityNumber: string;
  legalForm: string;
  contactName: string;
  contactEmail: string;
  status: string;
};
export type Engagement = {
  id: PublicId;
  publicId: PublicId;
  clientId: PublicId;
  clientName: string;
  charityNumber: string;
  periodEnd: string;
  periodStart: string | null;
  accountingBasis: string;
  grossIncome: number;
  grossAssets: number;
  materiality: number;
  risk: string;
  status: string;
  jurisdiction: string;
  jurisdictionRuleSetId: number | null;
  fundProfile: string;
  complexity: string;
  governingDocumentAudit: boolean;
  funderAudit: boolean;
  commissionAudit: boolean;
  groupAccountsRequired: boolean;
  scopeConclusion: string;
  methodologyVersion: string;
  qualityReviewMode: string;
  qualityReviewStatus: string;
  qualityReviewConclusion: string;
  qualityReviewedBy: string | null;
  qualityReviewedAt: string | null;
  trusteeApproved: boolean;
  materialSignificanceAssessed: boolean;
  reportConclusion: string | null;
  lockedAt: string | null;
  lockedBy: string | null;
  reopenedAt: string | null;
  reopenedBy: string | null;
  reopenReason: string | null;
  rowVersion: number;
};
export type Task = {
  id: PublicId;
  publicId: PublicId;
  engagementId: PublicId;
  direction: number;
  title: string;
  objective: string;
  phase: string;
  guidance: string;
  isCustom: boolean;
  status: TaskStatus;
  conclusion: string;
  preparedBy: string | null;
  preparedAt: string | null;
  reviewedBy: string | null;
  reviewedAt: string | null;
  rowVersion: number;
};
export type Procedure = {
  id: PublicId;
  publicId: PublicId;
  taskId: PublicId;
  sequence: number;
  text: string;
  guidance: string;
  applicability: "APPLICABLE" | "NOT_APPLICABLE" | "ESCALATED";
  applicabilityRationale: string;
  concernIdentified: boolean;
  concernSummary: string;
  evidenceSummary: string;
  workPerformed: string;
  conclusion: string;
  status: TaskStatus;
  preparedBy: string | null;
  preparedAt: string | null;
  reviewedBy: string | null;
  reviewedAt: string | null;
  completed: boolean;
  completedBy: string | null;
  completedAt: string | null;
  rowVersion: number;
};
export type EvidenceRequest = {
  id: PublicId;
  publicId: PublicId;
  engagementId: PublicId;
  taskId: PublicId | null;
  procedureId: PublicId | null;
  reference: string;
  title: string;
  description: string;
  contactName: string;
  contactEmail: string;
  dueDate: string;
  status: string;
  createdAt: string;
  receivedAt: string | null;
};
export type Comment = {
  id: PublicId;
  publicId: PublicId;
  engagementId: PublicId;
  taskId: PublicId | null;
  requestId: PublicId | null;
  authorEmail: string;
  authorName: string;
  visibility: string;
  body: string;
  createdAt: string;
};
export type ConversationThread = {
  id: PublicId;
  publicId: PublicId;
  engagementId: PublicId;
  requestId: PublicId | null;
  subject: string;
  category: "GENERAL" | "EVIDENCE" | "GOVERNANCE" | "REPORTING" | "TECHNICAL";
  priority: "NORMAL" | "HIGH" | "URGENT";
  status: "OPEN" | "WAITING_CLIENT" | "WAITING_PRACTICE" | "RESOLVED";
  assignedTo: string | null;
  createdBy: string;
  lastMessageAt: string;
  resolvedAt: string | null;
  resolvedBy: string | null;
  createdAt: string;
  updatedAt: string;
};
export type ConversationParticipant = {
  id: PublicId;
  publicId: PublicId;
  threadId: PublicId;
  email: string;
  name: string;
  participantType: "PRACTICE" | "CLIENT";
  notificationsEnabled: boolean;
  lastReadAt: string | null;
  createdAt: string;
};
export type ConversationMessage = {
  id: PublicId;
  publicId: PublicId;
  threadId: PublicId;
  replyToMessageId: PublicId | null;
  authorEmail: string;
  authorName: string;
  authorType: "PRACTICE" | "CLIENT" | "SYSTEM";
  body: string;
  deliveryStatus: "DELIVERED";
  createdAt: string;
};
export type ReviewNote = {
  id: PublicId;
  publicId: PublicId;
  engagementId: PublicId;
  taskId: PublicId | null;
  reference: string;
  title: string;
  body: string;
  severity: string;
  status: string;
  raisedBy: string;
  response: string | null;
  clearedBy: string | null;
  createdAt: string;
};
export type DocumentRecord = {
  id: PublicId;
  publicId: PublicId;
  engagementId: PublicId;
  requestId: PublicId | null;
  taskId: PublicId | null;
  procedureId: PublicId | null;
  concernId: PublicId | null;
  conversationThreadId: PublicId | null;
  conversationMessageId: PublicId | null;
  fileSection: string;
  fileName: string;
  mimeType: string;
  byteSize: number;
  sha256: string;
  uploadedBy: string;
  malwareStatus: string;
  createdAt: string;
};
export type PermanentDocument = {
  id: PublicId;
  publicId: PublicId;
  clientId: PublicId;
  category: string;
  fileName: string;
  mimeType: string;
  byteSize: number;
  sha256: string;
  uploadedBy: string;
  status: string;
  createdAt: string;
};
export type AuditEvent = {
  id: PublicId;
  publicId: PublicId;
  engagementId: PublicId | null;
  actorEmail: string;
  action: string;
  entityType: string;
  entityId: string;
  detail: string;
  createdAt: string;
};
export type TeamMember = {
  id: PublicId;
  publicId: PublicId;
  email: string;
  name: string;
  role: string;
  status: string;
  createdAt: string;
};
export type WorkpaperVersion = {
  id: PublicId;
  publicId: PublicId;
  taskId: PublicId;
  version: number;
  conclusion: string;
  status: string;
  contentHash: string;
  actorEmail: string;
  createdAt: string;
};
export type Signoff = {
  id: PublicId;
  publicId: PublicId;
  engagementId: PublicId;
  taskId: PublicId | null;
  procedureId: PublicId | null;
  type: string;
  statement: string;
  snapshotHash: string;
  signedBy: string;
  signedAt: string;
};
export type Trustee = {
  id: PublicId;
  publicId: PublicId;
  clientId: PublicId;
  personType: string;
  name: string;
  email: string | null;
  role: string;
  appointmentDate: string | null;
  resignationDate: string | null;
  status: string;
  createdAt: string;
};
export type ClientUser = {
  id: PublicId;
  publicId: PublicId;
  clientId: PublicId;
  name: string;
  email: string;
  role: string;
  status: string;
  lastAccessAt: string | null;
  createdAt: string;
};
export type Concern = {
  id: PublicId;
  publicId: PublicId;
  engagementId: PublicId;
  taskId: PublicId | null;
  procedureId: PublicId | null;
  reference: string;
  sourceType: string;
  category: string;
  title: string;
  description: string;
  severity: string;
  status: string;
  targetedResponse: string;
  managementResponse: string;
  examinerConclusion: string;
  reportingAssessment: string;
  resolution: string;
  owner: string | null;
  createdBy: string;
  submittedBy: string | null;
  submittedAt: string | null;
  reviewedBy: string | null;
  reviewedAt: string | null;
  reviewConclusion: string;
  closureHash: string | null;
  resolvedBy: string | null;
  resolvedAt: string | null;
  reopenedBy: string | null;
  reopenedAt: string | null;
  reopenReason: string | null;
  createdAt: string;
  updatedAt: string;
};
export type ConcernEvent = {
  id: PublicId;
  publicId: PublicId;
  concernId: PublicId;
  engagementId: PublicId;
  eventType: string;
  body: string;
  metadata: string;
  actorEmail: string;
  actorName: string;
  createdAt: string;
};
export type PracticeSettings = {
  concernReviewMode: string;
  requireIndependentConcernClosure: boolean;
  allowProcedureSelfReview: boolean;
  defaultQualityReviewMode: string;
  fileLockDeadlineDays: number;
  retentionYears: number;
  updatedBy: string;
  updatedAt: string;
};
export type FileLockEvent = {
  id: PublicId;
  publicId: PublicId;
  engagementId: PublicId;
  action: string;
  reason: string;
  snapshotHash: string;
  actorEmail: string;
  createdAt: string;
};
export type TbImport = {
  id: PublicId;
  publicId: PublicId;
  engagementId: PublicId;
  documentId: PublicId | null;
  version: number;
  fileName: string;
  sourceFormat: string;
  status: string;
  rowCount: number;
  debitTotal: number;
  creditTotal: number;
  netTotal: number;
  isBalanced: boolean;
  validationIssues: string;
  analysisConclusion: string;
  preparedBy: string | null;
  preparedAt: string | null;
  reviewedBy: string | null;
  reviewedAt: string | null;
  uploadedBy: string;
  createdAt: string;
};
export type TbAccount = {
  id: PublicId;
  publicId: PublicId;
  tbImportId: PublicId;
  accountCode: string;
  accountName: string;
  fund: string;
  statementLine: string;
  noteReference: string;
  debit: number;
  credit: number;
  currentBalance: number;
  priorBalance: number;
  budgetBalance: number;
  mappingStatus: string;
  createdAt: string;
};
export type TbAnalytic = {
  id: PublicId;
  publicId: PublicId;
  engagementId: PublicId;
  tbImportId: PublicId;
  accountId: PublicId | null;
  type: string;
  title: string;
  expectation: string;
  actual: number;
  comparator: number;
  variance: number;
  variancePercent: number;
  significanceThreshold: number;
  severity: string;
  status: string;
  explanation: string;
  targetedWork: string;
  conclusion: string;
  linkedTaskId: PublicId | null;
  linkedProcedureId: PublicId | null;
  concernId: PublicId | null;
  preparedBy: string | null;
  preparedAt: string | null;
  reviewedBy: string | null;
  reviewedAt: string | null;
  createdAt: string;
};
export type TbReconciliation = {
  id: PublicId;
  publicId: PublicId;
  engagementId: PublicId;
  tbImportId: PublicId;
  statementLine: string;
  tbAmount: number;
  accountsAmount: number;
  difference: number;
  status: string;
  explanation: string;
  preparedBy: string | null;
  preparedAt: string | null;
  reviewedBy: string | null;
  reviewedAt: string | null;
  createdAt: string;
};
export type Jurisdiction = {
  id: number;
  code: string;
  name: string;
  regulator: string;
  regulatorUrl: string;
  status: string;
  updatedBy: string;
  updatedAt: string;
};
export type JurisdictionRuleSet = {
  id: number;
  jurisdictionId: number;
  version: string;
  status: "DRAFT" | "PUBLISHED" | "RETIRED";
  effectiveFrom: string;
  effectiveTo: string | null;
  effectiveDateBasis: "PERIOD_START" | "PERIOD_END";
  examinationFloor: number;
  qualificationFloor: number;
  auditIncome: number;
  auditIncomeInclusive: boolean;
  assetIncomeFloor: number;
  auditAssets: number;
  qualificationFloorInclusive: boolean;
  allCharitiesScrutinised: boolean;
  assetTestBasis: "INCOME_AND_ASSETS" | "ACCRUALS_ASSETS" | "NONE";
  notes: string;
  sourceTitle: string;
  sourceUrl: string;
  publishedAt: string | null;
  createdBy: string;
  createdAt: string;
  updatedBy: string;
  updatedAt: string;
};
export type OrganisationType = {
  id: number;
  code: string;
  name: string;
  status: string;
  updatedBy: string;
  updatedAt: string;
};
export type AppState = {
  practiceName: string;
  actor: {
    kind: "INTERNAL" | "CLIENT";
    name: string;
    email: string;
    role: string;
    clientIds: PublicId[];
    clientRoles?: Record<PublicId, string>;
  };
  portalProgress?: Array<{
    engagementId: PublicId;
    totalTasks: number;
    reviewedTasks: number;
  }>;
  clients: Client[];
  engagements: Engagement[];
  tasks: Task[];
  procedures: Procedure[];
  requests: EvidenceRequest[];
  comments: Comment[];
  conversations: ConversationThread[];
  conversationParticipants: ConversationParticipant[];
  conversationMessages: ConversationMessage[];
  notes: ReviewNote[];
  documents: DocumentRecord[];
  permanentDocuments: PermanentDocument[];
  audit: AuditEvent[];
  users: TeamMember[];
  versions: WorkpaperVersion[];
  signoffs: Signoff[];
  trustees: Trustee[];
  clientUsers: ClientUser[];
  concerns: Concern[];
  concernEvents: ConcernEvent[];
  lockEvents: FileLockEvent[];
  tbImports: TbImport[];
  tbAccounts: TbAccount[];
  tbAnalytics: TbAnalytic[];
  tbReconciliations: TbReconciliation[];
  jurisdictions: Jurisdiction[];
  jurisdictionRuleSets: JurisdictionRuleSet[];
  organisationTypes: OrganisationType[];
  practiceSettings: PracticeSettings | null;
};
