export type Direction = {
  id: number;
  title: string;
  objective: string;
  phase: "Acceptance" | "Planning" | "Fieldwork" | "Completion";
  applies: "All" | "Accruals" | "All (part for R&P)";
  procedures: string[];
};

export const directions: Direction[] = [
  { id: 1, phase: "Acceptance", applies: "All", title: "Eligibility for independent examination", objective: "Confirm that neither charity law, company law, the governing document nor another obligation requires an audit.", procedures: ["Recalculate gross income and aggregate assets", "Consider subsidiaries, branches and group thresholds", "Inspect the governing document and funding conditions", "Confirm the accounting basis is permitted"] },
  { id: 2, phase: "Acceptance", applies: "All", title: "Independence and competence", objective: "Document the examiner’s independence, objectivity, experience and any required professional qualification.", procedures: ["Complete relationship and financial-interest declaration", "Assess perceived as well as actual threats", "Confirm competence and professional body eligibility", "Record safeguards or decline the appointment"] },
  { id: 3, phase: "Planning", applies: "All", title: "Record the examination", objective: "Create a sufficient record of the approach, evidence, conclusions and significant judgements for every applicable Direction.", procedures: ["Establish indexed workpapers", "Cross-reference evidence and conclusions", "Record preparer and reviewer sign-offs", "Retain a complete audit trail"] },
  { id: 4, phase: "Planning", applies: "All", title: "Plan the examination", objective: "Understand the charity and tailor proportionate procedures to its activities, systems, funds and risks.", procedures: ["Read prior accounts and governing document", "Understand activities, funds and accounting systems", "Determine materiality and significant areas", "Document timetable and information requirements"] },
  { id: 5, phase: "Fieldwork", applies: "All", title: "Accounting records", objective: "Check that accounting records are kept to the standard required by law.", procedures: ["Inspect cashbook, ledgers and supporting records", "Check completeness and clarity of entries", "Review bank reconciliations", "Investigate gaps or unexplained adjustments"] },
  { id: 6, phase: "Fieldwork", applies: "All", title: "Accounts agree to records", objective: "Confirm that the accounts are consistent with the underlying accounting records.", procedures: ["Agree primary statements to trial balance or cashbook", "Reconcile fund movements", "Trace material balances", "Document and clear differences"] },
  { id: 7, phase: "Fieldwork", applies: "Accruals", title: "Related-party disclosures", objective: "For accruals accounts, determine whether related-party transactions are properly disclosed.", procedures: ["Obtain trustee and related-party declarations", "Search ledgers and minutes for transactions", "Assess completeness of names, relationships and amounts", "Agree disclosures to evidence"] },
  { id: 8, phase: "Fieldwork", applies: "All (part for R&P)", title: "Policies, estimates and fund accounting", objective: "Assess significant estimates, judgements, policies and the accounting treatment of restricted, endowment and unrestricted funds.", procedures: ["Review significant estimates and judgements", "Check consistency and suitability of policies", "Test fund classification and transfers", "Challenge unusual treatments"] },
  { id: 9, phase: "Fieldwork", applies: "All (part for R&P)", title: "Financial circumstances and going concern", objective: "Check trustees’ consideration of the charity’s financial circumstances and, for accruals accounts, their going-concern assessment.", procedures: ["Review budgets, forecasts and post-year-end information", "Inspect trustees’ assessment and approval", "Consider liquidity and funding dependencies", "Evaluate the adequacy of disclosures"] },
  { id: 10, phase: "Fieldwork", applies: "All", title: "Form and content of accounts", objective: "Check compliance with the applicable statutory form and content requirements.", procedures: ["Identify legal form and accounting framework", "Complete disclosure checklist", "Check statement titles, comparative information and notes", "Record departures and required amendments"] },
  { id: 11, phase: "Fieldwork", applies: "All", title: "Analytical review and follow-up", objective: "Identify unexpected relationships, movements and items, then obtain explanations and evidence.", procedures: ["Compare current and prior periods", "Calculate relevant ratios and expectations", "Investigate significant or unusual variances", "Corroborate management explanations"] },
  { id: 12, phase: "Completion", applies: "All", title: "Trustees’ annual report", objective: "Compare the trustees’ annual report with the accounts and address material inconsistencies.", procedures: ["Read the complete trustees’ annual report", "Cross-check financial and narrative information", "Review public benefit and reserves disclosures", "Resolve material inconsistencies"] },
  { id: 13, phase: "Completion", applies: "All", title: "Examiner’s report", objective: "Prepare, date and sign a report containing all legally required statements and any necessary disclosures.", procedures: ["Evaluate all findings and uncorrected matters", "Complete material-significance assessment", "Select and review the appropriate report wording", "Confirm trustee approval precedes report signature"] }
];

const commonJurisdictionProgramme: Omit<Direction, "id">[] = [
  { phase: "Acceptance", applies: "All", title: "Statutory eligibility and accounting framework", objective: "Confirm the permitted external scrutiny and accounting route under the applicable jurisdiction, legal form and governing document.", procedures: ["Confirm registration and legal form", "Recalculate income and asset thresholds", "Inspect audit requirements and third-party conditions", "Record the applicable rule-set version"] },
  { phase: "Acceptance", applies: "All", title: "Independence, competence and appointment", objective: "Record independence, competence, any required professional qualification and the terms of appointment.", procedures: ["Complete independence and relationship checks", "Assess competence for the charity's size and complexity", "Verify professional qualification where required", "Approve or decline the appointment"] },
  { phase: "Planning", applies: "All", title: "Understanding the charity", objective: "Understand the charity's purposes, governance, activities, funds, systems and operating environment.", procedures: ["Read the governing document and prior reports", "Understand activities, governance and public benefit", "Document funds and accounting systems", "Identify significant changes and regulatory matters"] },
  { phase: "Planning", applies: "All", title: "Proportionate examination plan", objective: "Plan enquiry, analytical review and targeted verification responsive to the charity's circumstances.", procedures: ["Identify significant and unusual areas", "Set a planning significance threshold", "Tailor procedures to identified risks and concerns", "Agree timetable and information requirements"] },
  { phase: "Fieldwork", applies: "All", title: "Accounting records and books", objective: "Determine whether accounting records support the annual accounts and satisfy the applicable legal requirements.", procedures: ["Inspect cashbooks, ledgers and source records", "Review bank reconciliations", "Investigate gaps and unexplained entries", "Conclude on record-keeping adequacy"] },
  { phase: "Fieldwork", applies: "All", title: "Accounts agreement and reconciliation", objective: "Confirm the accounts agree to the underlying records and that material differences are resolved.", procedures: ["Agree statements to the trial balance or cashbook", "Reconcile bank, fund and control accounts", "Trace material balances to supporting schedules", "Record and clear differences"] },
  { phase: "Fieldwork", applies: "All", title: "Income and incoming resources", objective: "Use analytical review and targeted checks to address unusual or significant income movements.", procedures: ["Compare income streams with prior year and expectations", "Enquire into unusual or material movements", "Corroborate selected explanations", "Consider completeness and fund restrictions"] },
  { phase: "Fieldwork", applies: "All", title: "Expenditure and application of funds", objective: "Consider whether significant expenditure is supported, properly classified and consistent with charitable purposes.", procedures: ["Analyse expenditure movements and classifications", "Target unusual or material items", "Consider trustee and related-party payments", "Assess consistency with purposes and restrictions"] },
  { phase: "Fieldwork", applies: "All (part for R&P)", title: "Assets, liabilities and commitments", objective: "Address material assets, liabilities, commitments, estimates and post-year-end matters on a proportionate basis.", procedures: ["Review material balance movements", "Inspect support for selected balances", "Consider estimates, commitments and contingencies", "Review post-year-end information"] },
  { phase: "Fieldwork", applies: "All", title: "Funds, reserves and financial circumstances", objective: "Consider fund accounting, reserves, liquidity and the charity's financial circumstances.", procedures: ["Reconcile restricted, unrestricted and endowment funds", "Review transfers and deficit funds", "Consider budgets, liquidity and funding dependencies", "Assess reserves and going-concern disclosures"] },
  { phase: "Fieldwork", applies: "All", title: "Analytical review and targeted follow-up", objective: "Identify unexpected relationships or items and obtain explanations with proportionate corroboration.", procedures: ["Compare current, prior and budget information", "Develop relevant expectations and ratios", "Investigate significant or unusual variances", "Conclude on targeted follow-up"] },
  { phase: "Completion", applies: "All", title: "Trustees' report and statutory presentation", objective: "Check the accounts and trustees' report for the form, content and consistency required by the applicable framework.", procedures: ["Complete the jurisdiction-specific presentation checklist", "Read the trustees' annual report", "Cross-check narrative and financial information", "Resolve material omissions or inconsistencies"] },
  { phase: "Completion", applies: "All", title: "Examiner reporting and regulated matters", objective: "Evaluate findings, reporting obligations and the appropriate independent examiner's report.", procedures: ["Evaluate unresolved and uncorrected matters", "Assess matters of material significance", "Select jurisdiction-appropriate report wording", "Confirm trustee approval and controlled sign-off"] },
];

export function programmeForJurisdiction(jurisdiction: string): Direction[] {
  if (jurisdiction === "ENGLAND_WALES") return directions;
  return commonJurisdictionProgramme.map((item, index) => ({
    ...item,
    id: index + 1,
  }));
}

export type Status = "Not started" | "In progress" | "Prepared" | "Reviewed";

export const initialStatuses: Record<number, Status> = {
  1: "Reviewed", 2: "Reviewed", 3: "Prepared", 4: "Reviewed", 5: "Prepared", 6: "In progress",
  7: "In progress", 8: "In progress", 9: "Not started", 10: "In progress", 11: "Prepared", 12: "Not started", 13: "Not started"
};
